### ISSUE TITLE
Some questions on the dx_mapping_unsored.csv updated in commit a5ed494

### ISSUE THREAD

**Issue by wenh06** [physionetchallenges/evaluation-2021#6]
Why does the column `Ningbo` disappear in `dx_mapping_unscored.csv`? What does the name of the new column `Var12` mean? The column `Total` is not really "total" I think, since some values are 0 in this column.

**Comment by matthewreyna** [comment]
Thank you for your observation. Two of the columns were misnamed: `Total` should have been `Ningbo`, and `Var12` should have been `Total`. They have been corrected.
